apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: llm-service
    spec:
      containers:
      - name: llm-service
        image: shaohung/llm-api:v1.0
        ports:
        - containerPort: 8002
        env:
        - name: OLLAMA_HOST
          value: "10.20.1.95:11434"
        livenessProbe:
          httpGet:
            path: /
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 120
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: default
spec:
  selector:
    app: llm-service
  ports:
  - port: 8002
    nodePort: 30082
  type: NodePort