apiVersion: apps/v1
kind: Deployment
metadata:
  name: rerank-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rerank-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rerank-service
    spec:
      containers:
      - name: rerank-service
        image: shaohung/rerank-api:v1.0
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 120
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: rerank-service
  namespace: default
spec:
  selector:
    app: rerank-service
  ports:
  - port: 8001
    nodePort: 30081
  type: NodePort