apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieval-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: retrieval-service
    spec:
      containers:
      - name: retrieval-service
        image: shaohung/retrieval-api:v1.0
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_HOST
          value: "10.20.1.95:11433"
        - name: QDRANT_URL
          value: "http://10.0.0.201:6335"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 120
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: retrieval-service
  namespace: default
spec:
  selector:
    app: retrieval-service
  ports:
  - port: 8000
    nodePort: 30080
  type: NodePort